label: ""
$type: compositeField
layout:
  $type: stacked
itemProvider:
  $type: currentItemProvider
properties:
  templatesSortOrder: !include:/standard-template-kit/includes/dialogs/w2p/includes/sortOrderTemplates.yaml
  templatesPerPage: !include:/standard-template-kit/includes/dialogs/mpSearch/includes/perPage.yaml
  templatesPerRow: !include:/standard-template-kit/includes/dialogs/mpSearch/includes/perRow.yaml
  templatesDefaultView: !include:/standard-template-kit/includes/dialogs/mpSearch/includes/defaultView.yaml