label: "Layouts Positions"
$type: compositeField
layout:
  $type: horizontal
itemProvider:
  $type: currentItemProvider
properties:
  descLinkVerticalPosition: !include:/standard-template-kit/includes/dialogs/specialLayoutComponent/verticalPosition.yaml
  linkPosition: !include:/standard-template-kit/includes/dialogs/specialLayoutComponent/linkPosition.yaml  
