label: Configuration Page (Basic Components)
form:
  properties:
    title:
      label: Title
      $type: textField
    hide: 
      label: Hide in Navigation
      buttonLabel: yes/no
      $type: checkBoxField