title: Border Teaser List Configuration
dialog: standard-template-kit:components/grouping/config/borderTeaserListConfig
areas:
areas:
  column1: &column1
    title: Border Teasers
    availableComponents:
      textLink:
        id: standard-template-kit:components/advanced/borderTeaser
