title: Card Teaser List Configuration
dialog: standard-template-kit:components/grouping/config/cardTeaserListConfig
areas:
areas:
  column1: &column1
    title: Card Teasers
    availableComponents:
      textLink:
        id: standard-template-kit:components/advanced/cardTeaser
