title: Text & Link List Configuration
dialog: standard-template-kit:components/grouping/config/textLinkListConfig
areas:
  column1: &column1
    title: Text & Link Components
    availableComponents:
      textLink:
        id: standard-template-kit:components/advanced/textLink