label: Accordion
wide: true
form:
  properties:       

    title: !include:/standard-template-kit/includes/dialogs/accordion/title.yaml
    titleStyles: !include:/standard-template-kit/includes/dialogs/accordion/titleStyles.yaml
    titleDropdowns: !include:/standard-template-kit/includes/dialogs/accordion/titleDropdowns.yaml
    chevronStyles: !include:/standard-template-kit/includes/dialogs/accordion/chevronStyles.yaml
    accordionInnerPadding: !include:/standard-template-kit/includes/dialogs/accordion/accordionInnerPadding.yaml

    styleName: !include:/standard-template-kit/includes/dialogs/shared/styleName.yaml    
    accordionOuterPadding: !include:/standard-template-kit/includes/dialogs/accordion/accordionOuterPadding.yaml
    backgroundWidthPosition: !include:/standard-template-kit/includes/dialogs/accordion/backgroundWidthPosition.yaml
    accordionBorder: !include:/standard-template-kit/includes/dialogs/accordion/border.yaml
   
  
  layout:
    $type: tabbedLayout
    tabs:
      - name: title
      - label: Title Settings
        fields:
          - name: title      
          - name: titleDropdowns
          - name: titleStyles
          - name: accordionInnerPadding  
          - name: chevronStyles  
      - name: styles
      - label: Accordion Settings
        fields:
          - name: styleName   
          - name: backgroundWidthPosition    
          - name: accordionBorder      
          - name: accordionOuterPadding    