label: Card Teaser Config
wide: true
form:
  properties:

    headline: !include:/standard-template-kit/includes/dialogs/text/headline.yaml
    headlineDropdowns: !include:/standard-template-kit/includes/dialogs/text/headlineDropdowns.yaml
    headlineDropdowns1: !include:/standard-template-kit/includes/dialogs/text/headlineDropdowns1.yaml
    headlineTextStyles: !include:/standard-template-kit/includes/dialogs/text/headlineTextStyles.yaml
    headlinePadding: !include:/standard-template-kit/includes/dialogs/text/headlinePadding.yaml

    description: !include:/standard-template-kit/includes/dialogs/text/description.yaml   
    descriptionStyle: !include:/standard-template-kit/includes/dialogs/text/descriptionStyle.yaml
    descriptionPadding: !include:/standard-template-kit/includes/dialogs/text/descriptionPadding.yaml
    descriptionBorder: !include:/standard-template-kit/includes/dialogs/text/descriptionBorder.yaml
    
    image: !include:/standard-template-kit/includes/dialogs/image/imageRequired.yaml
    imageHeightPositionClickable: !include:/standard-template-kit/includes/dialogs/teasersShared/cardTeaser/imageHeightPositionClickable.yaml
    
    linkType: !include:/standard-template-kit/includes/dialogs/link/typeRequired.yaml
    linkLabel: !include:/standard-template-kit/includes/dialogs/link/label.yaml
    linkLocationIcon: !include:/standard-template-kit/includes/dialogs/teasersShared/cardTeaser/linkLocationIcon.yaml
    
    linkLabelStyles: !include:/standard-template-kit/includes/dialogs/link/labelStyles.yaml
    linkLabelDropdowns: !include:/standard-template-kit/includes/dialogs/link/linkLabelDropdowns.yaml
    labelPadding: !include:/standard-template-kit/includes/dialogs/link/labelPadding.yaml
    chevronStyles: !include:/standard-template-kit/includes/dialogs/link/chevronStyles.yaml
    linkStyles: !include:/standard-template-kit/includes/dialogs/link/linkStyles.yaml
    linkBackground: !include:/standard-template-kit/includes/dialogs/teasersShared/linkBackground.yaml
    linkPadding: !include:/standard-template-kit/includes/dialogs/link/padding.yaml
    linkBorder: !include:/standard-template-kit/includes/dialogs/link/border.yaml
    
    componentPadding: !include:/standard-template-kit/includes/dialogs/teasersShared/componentPadding.yaml
      label: Info Box
    componentBorder: !include:/standard-template-kit/includes/dialogs/teasersShared/componentBorder.yaml
      label: Info Box
    componentColorsBorders: !include:/standard-template-kit/includes/dialogs/teasersShared/cardTeaser/componentColorsBorders.yaml

    componentStyles: !include:/standard-template-kit/includes/dialogs/teasersShared/cardTeaser/componentStyles.yaml
    teaserLayout: !include:/standard-template-kit/includes/dialogs/teasersShared/teaserLayout.yaml
    descLinkLayout: !include:/standard-template-kit/includes/dialogs/teasersShared/descLinkLayout.yaml
    descLinkSettings: !include:/standard-template-kit/includes/dialogs/teasersShared/descLinkSettings.yaml
    linkPositions: !include:/standard-template-kit/includes/dialogs/teasersShared/linkPositions.yaml    

    linkStyleWithCheckbox: !include:/standard-template-kit/includes/dialogs/teasersShared/styleWithCheckbox/link.yaml
    styleName: !include:/standard-template-kit/includes/dialogs/shared/styleName.yaml
    
  layout:
    $type: tabbedLayout
    tabs:
      - name: text
      - label: Text 
        fields:
          - name: headline
          - name: description
      - name: image
      - label: Image 
        fields:
          - name: image
          - name: imageHeightPositionClickable
      - name: linkSetup
      - label: Link Setup
        fields:
          - name: linkType          
          - name: linkLabel
          - name: linkLocationIcon 
      - name: configStyles
      - label: Config Styles
        fields:
          - name: styleName
          - name: linkStyleWithCheckbox
      - name: layout
      - label: Layout
        fields:
          - name: componentStyles
          - name: teaserLayout          
          - name: descLinkLayout
          - name: descLinkSettings
          - name: linkPositions
      - name: headlineStyles
      - label: Headline Styles
        fields:
          - name: headlineDropdowns
          - name: headlineDropdowns1
          - name: headlineTextStyles         
          - name: headlinePadding
      - name: descriptionStyles
      - label: Description Styles
        fields:
          - name: descriptionStyle
          - name: descriptionPadding
          - name: descriptionBorder
      - name: linkStyles
      - label: Link Styles
        fields:        
          - name: linkLabelDropdowns
          - name: linkLabelStyles     
          - name: labelPadding    
          - name: chevronStyles      
          - name: linkStyles
          - name: linkBorder 
          - name: linkBackground             
          - name: linkPadding  
      - name: infoBoxStyles
      - label: Info Box Styles
        fields:                        
          - name: componentPadding          
          - name: componentBorder
          - name: componentColorsBorders