label: Global Layout Component Configuration
wide: true
form:
  properties:

    headline: !include:/standard-template-kit/includes/dialogs/text/headline.yaml
    headlineDropdowns: !include:/standard-template-kit/includes/dialogs/text/headlineDropdowns.yaml
    headlineDropdowns1: !include:/standard-template-kit/includes/dialogs/text/headlineDropdowns1.yaml
    headlineTextStyles: !include:/standard-template-kit/includes/dialogs/text/headlineTextStyles.yaml
    headlinePadding: !include:/standard-template-kit/includes/dialogs/text/headlinePadding.yaml

    description: !include:/standard-template-kit/includes/dialogs/text/description.yaml   
    descriptionStyle: !include:/standard-template-kit/includes/dialogs/text/descriptionStyle.yaml
    descriptionPadding: !include:/standard-template-kit/includes/dialogs/text/descriptionPadding.yaml
    descriptionBorder: !include:/standard-template-kit/includes/dialogs/text/descriptionBorder.yaml

    media1: !include:/standard-template-kit/includes/dialogs/globalLayoutComponent/media1Type.yaml
      label: Media 1 (Left Image/Video)
    media2: !include:/standard-template-kit/includes/dialogs/globalLayoutComponent/media2Type.yaml
      label: Media 2 (Right Image/Video)

    image1Border: !include:/standard-template-kit/includes/dialogs/globalLayoutComponent/image1Border.yaml   
    image1Padding: !include:/standard-template-kit/includes/dialogs/globalLayoutComponent/image1Padding.yaml   
    image2Border: !include:/standard-template-kit/includes/dialogs/globalLayoutComponent/image2Border.yaml   
    image2Padding: !include:/standard-template-kit/includes/dialogs/globalLayoutComponent/image2Padding.yaml   
    imagesBackgroundColors: !include:/standard-template-kit/includes/dialogs/globalLayoutComponent/imagesBackgroundColors.yaml   

    linkType: !include:/standard-template-kit/includes/dialogs/link/type.yaml
    linkLabel: !include:/standard-template-kit/includes/dialogs/link/label.yaml
    linkLocationIcon: !include:/standard-template-kit/includes/dialogs/link/locationIcon.yaml
    
    linkLabelStyles: !include:/standard-template-kit/includes/dialogs/link/labelStyles.yaml
    linkLabelDropdowns: !include:/standard-template-kit/includes/dialogs/link/linkLabelDropdowns.yaml
    labelPadding: !include:/standard-template-kit/includes/dialogs/link/labelPadding.yaml
    chevronStyles: !include:/standard-template-kit/includes/dialogs/link/chevronStyles.yaml
    linkStyles: !include:/standard-template-kit/includes/dialogs/link/linkStyles.yaml
    linkBackground: !include:/standard-template-kit/includes/dialogs/link/linkBackground.yaml
    linkPadding: !include:/standard-template-kit/includes/dialogs/link/padding.yaml
    linkBorder: !include:/standard-template-kit/includes/dialogs/link/border.yaml

    wrapperPadding: !include:/standard-template-kit/includes/dialogs/wrapper/wrapperPadding.yaml
      label: Component
    wrapperBorder: !include:/standard-template-kit/includes/dialogs/wrapper/wrapperBorder.yaml
      label: Component
    wrapperBackgroundColors: !include:/standard-template-kit/includes/dialogs/wrapper/wrapperBackgroundColors.yaml
      label: Component

    layout: !include:/standard-template-kit/includes/dialogs/globalLayoutComponent/layout.yaml
    descLinkLayout: !include:/standard-template-kit/includes/dialogs/teasersShared/descLinkLayout.yaml
    descLinkSettings: !include:/standard-template-kit/includes/dialogs/teasersShared/descLinkSettings.yaml
    linkPositions: !include:/standard-template-kit/includes/dialogs/globalLayoutComponent/linkPositions.yaml    
    imagesSettings: !include:/standard-template-kit/includes/dialogs/globalLayoutComponent/imagesSettings.yaml   
    imagesHeightFitPosition: !include:/standard-template-kit/includes/dialogs/globalLayoutComponent/imagesHeightFitPosition.yaml   

    linkStyleWithCheckbox: !include:/standard-template-kit/includes/dialogs/teasersShared/styleWithCheckbox/link.yaml
    styleName: !include:/standard-template-kit/includes/dialogs/shared/styleName.yaml
    
  layout:
    $type: tabbedLayout
    tabs:
      - name: text
      - label: Text 
        fields:
          - name: headline
          - name: description
      - name: media
      - label: Media
        fields:
          - name: media1
          - name: media2
      - name: linkSetup
      - label: Link Setup
        fields:
          - name: linkType          
          - name: linkLabel
          - name: linkLocationIcon 
      - name: configStyles
      - label: Config Styles
        fields:
          - name: styleName
          - name: linkStyleWithCheckbox
      - name: layout
      - label: Layout
        fields:
          - name: layout
          - name: descLinkLayout
          - name: descLinkSettings
          - name: linkPositions
          - name: imagesSettings
          - name: imagesHeightFitPosition
      - name: headlineStyles
      - label: Headline Styles
        fields:
          - name: headlineDropdowns
          - name: headlineDropdowns1
          - name: headlineTextStyles         
          - name: headlinePadding
      - name: descriptionStyles
      - label: Description Styles
        fields:
          - name: descriptionStyle
          - name: descriptionPadding
          - name: descriptionBorder
      - name: linkStyles
      - label: Link Styles
        fields:        
          - name: linkLabelDropdowns
          - name: linkLabelStyles     
          - name: labelPadding     
          - name: chevronStyles
          - name: linkStyles
          - name: linkBorder
          - name: linkBackground              
          - name: linkPadding  
      - name: mediaStyles
      - label: Media Styles
        fields:        
          - name: image1Border
          - name: image1Padding
          - name: image2Border
          - name: image2Padding
          - name: imagesBackgroundColors
      - name: componentStyles
      - label: Component Styles
        fields:              
          - name: wrapperPadding
          - name: wrapperBackgroundColors
          - name: wrapperBorder