label: Special Layout Component Configuration
wide: true
form:
  properties:

    headline: !include:/standard-template-kit/includes/dialogs/text/headline.yaml
    headlineDropdowns: !include:/standard-template-kit/includes/dialogs/text/headlineDropdowns.yaml
    headlineDropdowns1: !include:/standard-template-kit/includes/dialogs/text/headlineDropdowns1.yaml
    headlineTextStyles: !include:/standard-template-kit/includes/dialogs/text/headlineTextStyles.yaml
    headlinePadding: !include:/standard-template-kit/includes/dialogs/text/headlinePadding.yaml

    description: !include:/standard-template-kit/includes/dialogs/text/description.yaml   
    descriptionStyle: !include:/standard-template-kit/includes/dialogs/text/descriptionStyle.yaml
    descriptionPadding: !include:/standard-template-kit/includes/dialogs/text/descriptionPadding.yaml
    descriptionBorder: !include:/standard-template-kit/includes/dialogs/text/descriptionBorder.yaml

    media: !include:/standard-template-kit/includes/dialogs/specialLayoutComponent/mediaType.yaml

    imageBackgroundColors: !include:/standard-template-kit/includes/dialogs/image/backgroundColors.yaml
      label: Image/Video
    imagePositionFitWidthHeight: !include:/standard-template-kit/includes/dialogs/image/positionFitWidthHeight.yaml
      label: Image/Video
    imageBorder: !include:/standard-template-kit/includes/dialogs/image/border.yaml
      label: Image/Video
    imagePadding: !include:/standard-template-kit/includes/dialogs/image/padding.yaml
      label: Image/Video

    imageBackgroundPosition: !include:/standard-template-kit/includes/dialogs/image/wrapper/imageBackgroundPosition.yaml
      label: Media Wrapper
    imageWrapperBorder: !include:/standard-template-kit/includes/dialogs/image/wrapper/border.yaml
      label: Media Wrapper
    imageWrapperPadding: !include:/standard-template-kit/includes/dialogs/image/wrapper/padding.yaml
      label: Media Wrapper

    linkType: !include:/standard-template-kit/includes/dialogs/link/type.yaml
    linkLabel: !include:/standard-template-kit/includes/dialogs/link/label.yaml
    linkLocationIcon: !include:/standard-template-kit/includes/dialogs/link/locationIcon.yaml
    
    linkLabelStyles: !include:/standard-template-kit/includes/dialogs/link/labelStyles.yaml
    linkLabelDropdowns: !include:/standard-template-kit/includes/dialogs/link/linkLabelDropdowns.yaml
    labelPadding: !include:/standard-template-kit/includes/dialogs/link/labelPadding.yaml
    chevronStyles: !include:/standard-template-kit/includes/dialogs/link/chevronStyles.yaml
    linkStyles: !include:/standard-template-kit/includes/dialogs/link/linkStyles.yaml
    linkBackground: !include:/standard-template-kit/includes/dialogs/link/linkBackground.yaml
    linkPadding: !include:/standard-template-kit/includes/dialogs/link/padding.yaml
    linkBorder: !include:/standard-template-kit/includes/dialogs/link/border.yaml

    wrapperPadding: !include:/standard-template-kit/includes/dialogs/wrapper/wrapperPadding.yaml
      label: Component
    wrapperBorder: !include:/standard-template-kit/includes/dialogs/wrapper/wrapperBorder.yaml
      label: Component
    wrapperBackgroundColors: !include:/standard-template-kit/includes/dialogs/wrapper/wrapperBackgroundColors.yaml
      label: Component

    layout: !include:/standard-template-kit/includes/dialogs/specialLayoutComponent/layout.yaml
    layoutSettings1: !include:/standard-template-kit/includes/dialogs/specialLayoutComponent/layoutSettings1.yaml
    layoutSettings2: !include:/standard-template-kit/includes/dialogs/specialLayoutComponent/layoutSettings2.yaml

    linkStyleWithCheckbox: !include:/standard-template-kit/includes/dialogs/teasersShared/styleWithCheckbox/link.yaml
    styleName: !include:/standard-template-kit/includes/dialogs/shared/styleName.yaml
    
  layout:
    $type: tabbedLayout
    tabs:
      - name: text
      - label: Text 
        fields:
          - name: headline
          - name: description
      - name: media
      - label: Media
        fields:
          - name: media 
      - name: linkSetup
      - label: Link Setup
        fields:
          - name: linkType          
          - name: linkLabel
          - name: linkLocationIcon 
      - name: configStyles
      - label: Config Styles
        fields:
          - name: styleName
          - name: linkStyleWithCheckbox
          - name: imageStyleWithCheckbox
      - name: layout
      - label: Layout
        fields:
          - name: layout
          - name: layoutSettings1
          - name: layoutSettings2
      - name: headlineStyles
      - label: Headline Styles
        fields:
          - name: headlineDropdowns
          - name: headlineDropdowns1
          - name: headlineTextStyles         
          - name: headlinePadding
      - name: descriptionStyles
      - label: Description Styles
        fields:
          - name: descriptionStyle
          - name: descriptionPadding
          - name: descriptionBorder
      - name: linkStyles
      - label: Link Styles
        fields:        
          - name: linkLabelDropdowns
          - name: linkLabelStyles     
          - name: labelPadding     
          - name: chevronStyles
          - name: linkStyles
          - name: linkBorder
          - name: linkBackground              
          - name: linkPadding  
      - name: mediaStyles
      - label: Media Styles
        fields:        
          - name: imagePositionFitWidthHeight
          - name: imagePadding
          - name: imageBackgroundColors
          - name: imageBorder
      - name: mediaWrapperStyles
      - label: Media Wrapper Styles
        fields:          
          - name: imageBackgroundPosition
          - name: imageWrapperBorder
          - name: imageWrapperPadding
      - name: componentStyles
      - label: Component Styles
        fields:              
          - name: wrapperPadding
          - name: wrapperBackgroundColors
          - name: wrapperBorder