label: Card Teaser List Configuration
wide: true
form:
  properties:

    styleName: !include:/standard-template-kit/includes/dialogs/shared/styleName.yaml
    layout: !include:/standard-template-kit/includes/dialogs/listComponents/listLayout.yaml  
    headline: !include:/standard-template-kit/includes/dialogs/text/headline.yaml
    gapsWidthPosition: !include:/standard-template-kit/includes/dialogs/listComponents/gapsWidthPosition.yaml
      label: List
    padding: !include:/standard-template-kit/includes/dialogs/wrapper/wrapperPadding.yaml
      label: List
    border: !include:/standard-template-kit/includes/dialogs/wrapper/wrapperBorder.yaml
      label: List

    headlineDropdowns: !include:/standard-template-kit/includes/dialogs/text/headlineDropdowns.yaml
    headlineTextStyles: !include:/standard-template-kit/includes/dialogs/text/headlineTextStyles.yaml
    headlinePadding: !include:/standard-template-kit/includes/dialogs/text/headlinePadding.yaml            
    
  layout:
    $type: tabbedLayout
    tabs:
      - name: listSettings
      - label: List Settings
        fields:
          - name: styleName
          - name: layout   
          - name: headline       
          - name: gapsWidthPosition          
          - name: padding
          - name: border
      - name: titleStyles
      - label: Title Styles
        fields:
          - name: headlineDropdowns
          - name: headlineTextStyles
          - name: headlinePadding  