label: ""
$type: compositeField
layout:
  $type: horizontal
itemProvider:
  $type: currentItemProvider
properties:
  previewColor: !include:/standard-template-kit/includes/dialogs/corporateColors/previewColor.yaml
  previewFontColor: !include:/standard-template-kit/includes/dialogs/text/includes/fontColor.yaml
    label: Preview Font Color
  previewBorder: !include:/standard-template-kit/includes/dialogs/corporateColors/previewBorder.yaml
  previewBorderColor: !include:/standard-template-kit/includes/dialogs/corporateColors/previewBorderColor.yaml