label: ""
$type: compositeField
layout:
  $type: stacked
itemProvider:
  $type: currentItemProvider
properties:
  templatesSearchType: !include:/standard-template-kit/includes/dialogs/w2p/includes/templatesSearchType.yaml
  sortOrderTemplates: !include:/standard-template-kit/includes/dialogs/w2p/includes/sortOrderTemplates.yaml
  perPage: !include:/standard-template-kit/includes/dialogs/mpSearch/includes/perPage.yaml
  perRow: !include:/standard-template-kit/includes/dialogs/mpSearch/includes/perRow.yaml
  defaultView: !include:/standard-template-kit/includes/dialogs/mpSearch/includes/defaultView.yaml