label: Video Configuration
wide: true
form:
  properties:
    videoType: !include:/standard-template-kit/includes/dialogs/video/videoType.yaml
    
    styleName: !include:/standard-template-kit/includes/dialogs/shared/styleName.yaml
    padding: !include:/standard-template-kit/includes/dialogs/shared/padding.yaml
      label: Component
    backgroundColors: !include:/standard-template-kit/includes/dialogs/shared/backgroundColors.yaml
      label: Component
    border: !include:/standard-template-kit/includes/dialogs/shared/border.yaml
      label: Component
    widthHeightPosition: !include:/standard-template-kit/includes/dialogs/shared/widthHeightPosition.yaml
      label: Component

  layout:
    $type: tabbedLayout
    tabs:
      - name: data
      - label: Data
        fields:
          - name: videoType
      - name: videoSettings
      - label: Video Settings
        fields:
          - name: styleName
          - name: widthHeightPosition
          - name: padding                      
          - name: border  
          - name: backgroundColors  